services:

  wordpress:
    image: wordpress:hmdcc
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html


#   db:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_DATABASE: exampledb
#       MYSQL_USER: exampleuser
#       MYSQL_PASSWORD: examplepass
#       MYSQL_RANDOM_ROOT_PASSWORD: '1'
#     volumes:
#       - db:/var/lib/mysql

volumes:
  wordpress:
  # db:
