apiVersion: traefik.io/v1alpha1
kind: IngressRoute 
metadata:
  name: sitehmdcc-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.hmdcc.org.br`)
      kind: Rule      
      services:
        - name: service-sitehmdcc
          port: 80
    - match: Host(`hmdcc.org.br`)
      kind: Rule      
      services:
        - name: service-sitehmdcc
          port: 80
  tls:
    secretName: sitehmdcc-certificate-secret # deve ser o mesmo do Certificate
