apiVersion: v1
kind: PersistentVolume
metadata:
  name: senior-hostpath-pv
spec:
  capacity:
    storage: 2Gi # Use um tamanho que seja adequado para o seu uso
  accessModes:
    - ReadWriteMany # Permite que múltiplos pods acessem o volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/media/senior" # O caminho para o diretório no nó do Kubernetes
    type: DirectoryOrCreate 