apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: senior-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi # Deve ser igual ou menor que a capacidade do PV
  storageClassName: manual # Deve corresponder ao nome do PV
  volumeName: senior-hostpath-pv # Vincula o PVC ao PV