apiVersion: traefik.io/v1alpha1
kind: IngressRoute 
metadata:
  name: wordpress-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wp.hmdcc.org.br`)
      kind: Rule      
      services:
        - name: wordpress-service
          port: 80
  tls:
    secretName: wordpress-certificate-secret # deve ser o mesmo do Certificate
