apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-ingressroute-certificate
  namespace: default
spec:
  # Secret names are always required.
  secretName: wordpress-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames: # deve ser o mesmo do IngressRoute
    - wp.hmdcc.org.br